version: '3'

services:
  backend1:
    build: ./backend1
    image: alexismendozaa/backend1:latest
    ports:
      - "5000:5000"
    networks:
      - backend_network
    depends_on:
      - db

  backend2:
    build: ./backend2
    image: alexismendozaa/backend2:latest
    ports:
      - "5001:5001"
    networks:
      - backend_network
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: users_db
    ports:
      - "3306:3306"
    networks:
      - backend_network
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  backend_network:
    driver: bridge